apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: api-test-hpa
  namespace: api-test-namespace-dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    name: api-test
    kind: Deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 25
